export type Modality = "text" | "audio" | "multimodal" | "image" | "video" | "realtime-audio" | "speech-to-text" | "text-to-speech" | "other" | "text-to-image" | "text-to-video" | "text-to-audio" | "image-generation" | "video-generation" | "audio-generation";
export type ModelProvider = "Alibaba" | "Anthropic" | "AssemblyAI" | "Black Forest Labs" | "Cohere" | "DeepSeek" | "Deepgram" | "ElevenLabs" | "Google" | "IBM" | "Kuaishou" | "Luma AI" | "Meta" | "MiniMax" | "Mistral" | "Moonshot AI" | "OpenAI" | "Perplexity" | "Pika Labs" | "Runway" | "Stability AI" | "xAI";
export interface ModelPricing {
	id: string;
	displayName: string;
	apiName: string;
	provider: ModelProvider;
	modality: Modality;
	// Token pricing (text/multimodal LLMs)
	inputPricePer1M?: number | null; // $ per 1M input tokens (0 if not applicable)
	outputPricePer1M?: number | null; // $ per 1M output tokens (0 if not applicable)
	cachedInputPricePer1M?: number | null; // $ per 1M input tokens when using caching (null if no caching, 0 if free caching)
	contextLength?: number | null; // in tokens (0 if not applicable)
	// Capabilities
	supportsTemperature: boolean;
	supportsTopK: boolean;
	supportsFunctionCalling: boolean;
	// Audio pricing
	sttPricePer1Min?: number | null; // $ per minute (STT models)
	ttsPricePer1KChars?: number | null; // $ per 1K characters (TTS models)
	// Image pricing
	imagePricePerImage?: number | null; // $ per image generated
	imageResolution?: string | null; // e.g. "1024x1024"
	// Video pricing
	videoPricePerSecond?: number | null; // $ per second of video
	videoResolution?: string | null; // e.g. "720p"
	// Meta
	description?: string;
}

export const MODEL_PRICING: ModelPricing[] = [
	{
		id: "gpt-4o",
		displayName: "GPT-4o",
		apiName: "gpt-4o",
		provider: "OpenAI",
		modality: "multimodal",
		inputPricePer1M: 2.5,
		outputPricePer1M: 10,
		cachedInputPricePer1M: 1.25,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Flagship multimodal model with vision, audio, and text capabilities.",
	},
	{
		id: "gpt-4o-mini",
		displayName: "GPT-4o Mini",
		apiName: "gpt-4o-mini",
		provider: "OpenAI",
		modality: "multimodal",
		inputPricePer1M: 0.15,
		outputPricePer1M: 0.6,
		cachedInputPricePer1M: 0.075,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Cost-efficient small multimodal model, strong for high-volume tasks.",
	},
	{
		id: "gpt-4.1",
		displayName: "GPT-4.1",
		apiName: "gpt-4.1",
		provider: "OpenAI",
		modality: "multimodal",
		inputPricePer1M: 2.0,
		outputPricePer1M: 8.0,
		cachedInputPricePer1M: 0.5,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Instruction-following powerhouse with 1M context; excellent for agentic workflows.",
	},
	{
		id: "gpt-4.1-mini",
		displayName: "GPT-4.1 Mini",
		apiName: "gpt-4.1-mini",
		provider: "OpenAI",
		modality: "multimodal",
		inputPricePer1M: 0.4,
		outputPricePer1M: 1.6,
		cachedInputPricePer1M: 0.1,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Affordable GPT-4.1-class model with 1M context for high-volume tasks.",
	},
	{
		id: "gpt-4.1-nano",
		displayName: "GPT-4.1 Nano",
		apiName: "gpt-4.1-nano",
		provider: "OpenAI",
		modality: "text",
		inputPricePer1M: 0.1,
		outputPricePer1M: 0.4,
		cachedInputPricePer1M: 0.025,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Ultra-cheap nano model for simple high-volume classification and extraction.",
	},
	{
		id: "o3",
		displayName: "o3",
		apiName: "o3",
		provider: "OpenAI",
		modality: "text",
		inputPricePer1M: 10.0,
		outputPricePer1M: 40.0,
		cachedInputPricePer1M: 2.5,
		contextLength: 200000,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "OpenAI's most powerful reasoning model; excels at math, coding, and science.",
	},
	{
		id: "o3-mini",
		displayName: "o3-mini",
		apiName: "o3-mini",
		provider: "OpenAI",
		modality: "text",
		inputPricePer1M: 1.1,
		outputPricePer1M: 4.4,
		cachedInputPricePer1M: 0.55,
		contextLength: 200000,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Compact reasoning model optimized for cost-efficient STEM tasks.",
	},
	{
		id: "o4-mini",
		displayName: "o4-mini",
		apiName: "o4-mini",
		provider: "OpenAI",
		modality: "multimodal",
		inputPricePer1M: 1.1,
		outputPricePer1M: 4.4,
		cachedInputPricePer1M: 0.275,
		contextLength: 200000,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Efficient reasoning model with vision; strong on coding, math, and visual tasks.",
	},
	{
		id: "o1",
		displayName: "o1",
		apiName: "o1",
		provider: "OpenAI",
		modality: "text",
		inputPricePer1M: 15.0,
		outputPricePer1M: 60.0,
		cachedInputPricePer1M: 7.5,
		contextLength: 200000,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Original advanced reasoning model; thorough chain-of-thought inference.",
	},
	{
		id: "claude-opus-4-6",
		displayName: "Claude Opus 4.6",
		apiName: "claude-opus-4-6",
		provider: "Anthropic",
		modality: "multimodal",
		inputPricePer1M: 5.0,
		outputPricePer1M: 25.0,
		cachedInputPricePer1M: 0.5,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Anthropic's most capable model; frontier reasoning, coding, and enterprise agentic tasks.",
	},
	{
		id: "claude-sonnet-4-6",
		displayName: "Claude Sonnet 4.6",
		apiName: "claude-sonnet-4-6",
		provider: "Anthropic",
		modality: "multimodal",
		inputPricePer1M: 3.0,
		outputPricePer1M: 15.0,
		cachedInputPricePer1M: 0.3,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Best balance of intelligence and cost; high-throughput developer favorite with 1M context.",
	},
	{
		id: "claude-haiku-4-5",
		displayName: "Claude Haiku 4.5",
		apiName: "claude-haiku-4-5-20251001",
		provider: "Anthropic",
		modality: "multimodal",
		inputPricePer1M: 1.0,
		outputPricePer1M: 5.0,
		cachedInputPricePer1M: 0.1,
		contextLength: 200000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Fastest and most affordable Claude; ideal for speed-critical high-volume workloads.",
	},
	{
		id: "claude-opus-4-5",
		displayName: "Claude Opus 4.5",
		apiName: "claude-opus-4-5",
		provider: "Anthropic",
		modality: "multimodal",
		inputPricePer1M: 5.0,
		outputPricePer1M: 25.0,
		cachedInputPricePer1M: 0.5,
		contextLength: 200000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Previous flagship; industry-leading SWE-bench scores for autonomous coding.",
	},
	{
		id: "claude-sonnet-4-5",
		displayName: "Claude Sonnet 4.5",
		apiName: "claude-sonnet-4-5-20250929",
		provider: "Anthropic",
		modality: "multimodal",
		inputPricePer1M: 3.0,
		outputPricePer1M: 15.0,
		cachedInputPricePer1M: 0.3,
		contextLength: 200000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Recommended default model; best-in-class coding with strong agent capabilities.",
	},
	{
		id: "claude-3-5-sonnet",
		displayName: "Claude 3.5 Sonnet",
		apiName: "claude-3-5-sonnet-20241022",
		provider: "Anthropic",
		modality: "multimodal",
		inputPricePer1M: 3.0,
		outputPricePer1M: 15.0,
		cachedInputPricePer1M: 0.3,
		contextLength: 200000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Highly capable vision and text model; prior workhorse for production apps.",
	},
	{
		id: "claude-3-haiku",
		displayName: "Claude 3 Haiku",
		apiName: "claude-3-haiku-20240307",
		provider: "Anthropic",
		modality: "multimodal",
		inputPricePer1M: 0.25,
		outputPricePer1M: 1.25,
		cachedInputPricePer1M: 0.03,
		contextLength: 200000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Legacy lightweight model; still popular for low-cost classification tasks.",
	},
	{
		id: "gemini-3-1-pro",
		displayName: "Gemini 3.1 Pro",
		apiName: "gemini-3.1-pro-preview",
		provider: "Google",
		modality: "multimodal",
		inputPricePer1M: 2.0,
		outputPricePer1M: 12.0,
		cachedInputPricePer1M: 0.5,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Google's latest flagship reasoning model; frontier intelligence with superior search.",
	},
	{
		id: "gemini-3-flash",
		displayName: "Gemini 3 Flash",
		apiName: "gemini-3.0-flash",
		provider: "Google",
		modality: "multimodal",
		inputPricePer1M: 0.5,
		outputPricePer1M: 3.0,
		cachedInputPricePer1M: 0.125,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Balanced speed and capability; native multimodal with native audio generation.",
	},
	{
		id: "gemini-2-5-pro",
		displayName: "Gemini 2.5 Pro",
		apiName: "gemini-2.5-pro",
		provider: "Google",
		modality: "multimodal",
		inputPricePer1M: 1.25,
		outputPricePer1M: 10.0,
		cachedInputPricePer1M: 0.31,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Production-ready Google flagship; strong reasoning, coding, and analysis with 1M context.",
	},
	{
		id: "gemini-2-5-flash",
		displayName: "Gemini 2.5 Flash",
		apiName: "gemini-2.5-flash",
		provider: "Google",
		modality: "multimodal",
		inputPricePer1M: 0.3,
		outputPricePer1M: 2.5,
		cachedInputPricePer1M: 0.075,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Best value Google model; fast, affordable, supports thinking mode and 1M context.",
	},
	{
		id: "gemini-2-5-flash-lite",
		displayName: "Gemini 2.5 Flash-Lite",
		apiName: "gemini-2.5-flash-lite",
		provider: "Google",
		modality: "multimodal",
		inputPricePer1M: 0.1,
		outputPricePer1M: 0.4,
		cachedInputPricePer1M: 0.025,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Cheapest production Gemini model; ideal for high-volume simple tasks.",
	},
	{
		id: "gemini-2-0-flash",
		displayName: "Gemini 2.0 Flash",
		apiName: "gemini-2.0-flash",
		provider: "Google",
		modality: "multimodal",
		inputPricePer1M: 0.1,
		outputPricePer1M: 0.4,
		cachedInputPricePer1M: 0.025,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Previous generation Flash; deprecated June 2026 but still widely used.",
	},
	{
		id: "o4-mini-deep-research",
		displayName: "o4-mini Deep Research",
		apiName: "o4-mini-deep-research",
		provider: "OpenAI",
		modality: "text",
		inputPricePer1M: 2.0,
		outputPricePer1M: 8.0,
		cachedInputPricePer1M: 0.5,
		contextLength: 200000,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Deep research variant of o4-mini; real-time web data grounded responses.",
	},
	{
		id: "o3-deep-research",
		displayName: "o3 Deep Research",
		apiName: "o3-deep-research",
		provider: "OpenAI",
		modality: "text",
		inputPricePer1M: 10.0,
		outputPricePer1M: 40.0,
		cachedInputPricePer1M: 2.5,
		contextLength: 200000,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Deep research variant of o3 with transparent, auditable real-time web insights.",
	},
	{
		id: "deepseek-v4",
		displayName: "DeepSeek V4",
		apiName: "deepseek-chat",
		provider: "DeepSeek",
		modality: "text",
		inputPricePer1M: 0.3,
		outputPricePer1M: 0.5,
		cachedInputPricePer1M: 0.03,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "DeepSeek's latest flagship; 81% SWE-bench, best value frontier model.",
	},
	{
		id: "deepseek-v3-2",
		displayName: "DeepSeek V3.2",
		apiName: "deepseek-chat-v3-2",
		provider: "DeepSeek",
		modality: "text",
		inputPricePer1M: 0.28,
		outputPricePer1M: 0.42,
		cachedInputPricePer1M: 0.028,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Budget flagship with near-frontier quality; 671B MoE architecture.",
	},
	{
		id: "deepseek-r1",
		displayName: "DeepSeek R1",
		apiName: "deepseek-reasoner",
		provider: "DeepSeek",
		modality: "text",
		inputPricePer1M: 0.55,
		outputPricePer1M: 2.19,
		cachedInputPricePer1M: 0.14,
		contextLength: 128000,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Open-source reasoning model rivaling o1 at ~96% lower cost; chain-of-thought.",
	},
	{
		id: "mistral-large-3-2512",
		displayName: "Mistral Large 3",
		apiName: "mistral-large-2512",
		provider: "Mistral",
		modality: "text",
		inputPricePer1M: 0.5,
		outputPricePer1M: 1.5,
		cachedInputPricePer1M: null,
		contextLength: 262000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Mistral's flagship model; strong multilingual reasoning and long context.",
	},
	{
		id: "mistral-medium-3",
		displayName: "Mistral Medium 3",
		apiName: "mistral-medium-3",
		provider: "Mistral",
		modality: "multimodal",
		inputPricePer1M: 0.4,
		outputPricePer1M: 2.0,
		cachedInputPricePer1M: null,
		contextLength: 131000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Versatile mid-tier model with vision capabilities; released May 2025.",
	},
	{
		id: "mistral-small-3-1",
		displayName: "Mistral Small 3.1",
		apiName: "mistral-small-latest",
		provider: "Mistral",
		modality: "multimodal",
		inputPricePer1M: 0.2,
		outputPricePer1M: 0.6,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Budget-friendly Mistral model; great price-to-performance for most tasks.",
	},
	{
		id: "mistral-nemo",
		displayName: "Mistral NeMo",
		apiName: "open-mistral-nemo",
		provider: "Mistral",
		modality: "text",
		inputPricePer1M: 0.02,
		outputPricePer1M: 0.04,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Cheapest commercial LLM option; multilingual, open-weight, Apache 2.0 license.",
	},
	{
		id: "codestral-2508",
		displayName: "Codestral 2508",
		apiName: "codestral-2508",
		provider: "Mistral",
		modality: "text",
		inputPricePer1M: 0.3,
		outputPricePer1M: 0.9,
		cachedInputPricePer1M: null,
		contextLength: 256000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Coding specialist; 256K context for large codebases, fill-in-the-middle support.",
	},
	{
		id: "magistral-medium",
		displayName: "Magistral Medium",
		apiName: "magistral-medium-latest",
		provider: "Mistral",
		modality: "text",
		inputPricePer1M: 0.4,
		outputPricePer1M: 2.0,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Mistral's reasoning model; hybrid instruct, reasoning, and coding in one.",
	},
	{
		id: "devstral-medium",
		displayName: "Devstral Medium",
		apiName: "devstral-medium-latest",
		provider: "Mistral",
		modality: "text",
		inputPricePer1M: 0.4,
		outputPricePer1M: 2.0,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Agent-first coding model; designed for complex software engineering tasks.",
	},
	{
		id: "pixtral-large",
		displayName: "Pixtral Large",
		apiName: "pixtral-large-latest",
		provider: "Mistral",
		modality: "multimodal",
		inputPricePer1M: 2.0,
		outputPricePer1M: 6.0,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Mistral's frontier multimodal model; best-in-class text and vision capabilities.",
	},
	{
		id: "llama-4-maverick",
		displayName: "Llama 4 Maverick",
		apiName: "meta-llama/llama-4-maverick",
		provider: "Meta",
		modality: "multimodal",
		inputPricePer1M: 0.15,
		outputPricePer1M: 0.6,
		cachedInputPricePer1M: 0.075,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Meta's flagship open model; 400B MoE, multimodal, 1M context, commercial use.",
	},
	{
		id: "llama-4-scout",
		displayName: "Llama 4 Scout",
		apiName: "meta-llama/llama-4-scout",
		provider: "Meta",
		modality: "multimodal",
		inputPricePer1M: 0.15,
		outputPricePer1M: 0.6,
		cachedInputPricePer1M: 0.075,
		contextLength: 10000000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Long-context specialist; world-record 10M token window, single-GPU deployable.",
	},
	{
		id: "llama-3-3-70b",
		displayName: "Llama 3.3 70B",
		apiName: "meta-llama/llama-3.3-70b-instruct",
		provider: "Meta",
		modality: "text",
		inputPricePer1M: 0.18,
		outputPricePer1M: 0.35,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Highly capable open-source model; near GPT-4o quality at a fraction of the cost.",
	},
	{
		id: "llama-3-1-405b",
		displayName: "Llama 3.1 405B",
		apiName: "meta-llama/llama-3.1-405b-instruct",
		provider: "Meta",
		modality: "text",
		inputPricePer1M: 3.5,
		outputPricePer1M: 3.5,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Largest open Llama; GPT-4-class performance with open weights for self-hosting.",
	},
	{
		id: "llama-3-2-90b",
		displayName: "Llama 3.2 90B Vision",
		apiName: "meta-llama/llama-3.2-90b-vision-instruct",
		provider: "Meta",
		modality: "multimodal",
		inputPricePer1M: 0.8,
		outputPricePer1M: 0.8,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Open-source multimodal model; strong image understanding at accessible pricing.",
	},
	{
		id: "grok-4",
		displayName: "Grok 4",
		apiName: "grok-4",
		provider: "xAI",
		modality: "text",
		inputPricePer1M: 3.0,
		outputPricePer1M: 15.0,
		cachedInputPricePer1M: 0.75,
		contextLength: 256000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "xAI's flagship with real-time X/Twitter data access and web search built-in.",
	},
	{
		id: "grok-4-1-fast",
		displayName: "Grok 4.1 Fast",
		apiName: "grok-4.1-fast",
		provider: "xAI",
		modality: "text",
		inputPricePer1M: 0.2,
		outputPricePer1M: 0.5,
		cachedInputPricePer1M: 0.05,
		contextLength: 2000000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Ultra-fast, ultra-cheap Grok variant; world's largest 2M token context.",
	},
	{
		id: "grok-3-mini",
		displayName: "Grok 3 Mini",
		apiName: "grok-3-mini",
		provider: "xAI",
		modality: "text",
		inputPricePer1M: 0.3,
		outputPricePer1M: 0.5,
		cachedInputPricePer1M: null,
		contextLength: 131000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Budget Grok model with favorable output-to-input ratio for long-form generation.",
	},
	{
		id: "command-r-plus",
		displayName: "Command R+",
		apiName: "command-r-plus-08-2024",
		provider: "Cohere",
		modality: "text",
		inputPricePer1M: 2.5,
		outputPricePer1M: 10.0,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Cohere's flagship RAG-optimized model; enterprise search and complex tool use.",
	},
	{
		id: "command-r",
		displayName: "Command R",
		apiName: "command-r-08-2024",
		provider: "Cohere",
		modality: "text",
		inputPricePer1M: 0.15,
		outputPricePer1M: 0.6,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Balanced Cohere model; cost-effective for RAG, chatbots, and summarization.",
	},
	{
		id: "command-a",
		displayName: "Command A",
		apiName: "command-a-03-2025",
		provider: "Cohere",
		modality: "text",
		inputPricePer1M: 2.5,
		outputPricePer1M: 10.0,
		cachedInputPricePer1M: null,
		contextLength: 256000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Advanced agentic model with 256K context for large document processing.",
	},
	{
		id: "command-r7b",
		displayName: "Command R7B",
		apiName: "command-r7b-12-2024",
		provider: "Cohere",
		modality: "text",
		inputPricePer1M: 0.04,
		outputPricePer1M: 0.15,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Ultra-lightweight Cohere model; edge and on-device deployable.",
	},
	{
		id: "qwen3-235b",
		displayName: "Qwen3 235B A22B",
		apiName: "qwen/qwen3-235b-a22b",
		provider: "Alibaba",
		modality: "text",
		inputPricePer1M: 0.23,
		outputPricePer1M: 0.92,
		cachedInputPricePer1M: null,
		contextLength: 131000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Alibaba's flagship open MoE model; frontier performance at budget pricing.",
	},
	{
		id: "qwen-qwq-32b",
		displayName: "Qwen QwQ 32B",
		apiName: "qwen/qwq-32b",
		provider: "Alibaba",
		modality: "text",
		inputPricePer1M: 0.2,
		outputPricePer1M: 0.8,
		cachedInputPricePer1M: null,
		contextLength: 131000,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Open-source reasoning model comparable to o1-mini; math and coding specialist.",
	},
	{
		id: "gpt-4o-realtime",
		displayName: "GPT-4o Realtime",
		apiName: "gpt-4o-realtime-preview",
		provider: "OpenAI",
		modality: "realtime-audio",
		inputPricePer1M: 5.0,
		outputPricePer1M: 20.0,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Real-time voice API; text input $5/1M, audio input $100/1M, audio output $200/1M. Low-latency speech-to-speech.",
	},
	{
		id: "gpt-4o-mini-realtime",
		displayName: "GPT-4o Mini Realtime",
		apiName: "gpt-4o-mini-realtime-preview",
		provider: "OpenAI",
		modality: "realtime-audio",
		inputPricePer1M: 0.6,
		outputPricePer1M: 2.4,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Affordable real-time voice; text $0.60/1M, audio in $10/1M, audio out $20/1M tokens.",
	},
	{
		id: "gpt-4o-audio-preview",
		displayName: "GPT-4o Audio Preview",
		apiName: "gpt-4o-audio-preview",
		provider: "OpenAI",
		modality: "realtime-audio",
		inputPricePer1M: 2.5,
		outputPricePer1M: 10.0,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Async audio model via Chat Completions API; processes and generates audio content.",
	},
	{
		id: "gpt-4o-transcribe",
		displayName: "GPT-4o Transcribe",
		apiName: "gpt-4o-transcribe",
		provider: "OpenAI",
		modality: "speech-to-text",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Advanced STT: $0.006/min. Outperforms Whisper on accented/noisy audio. 100+ languages.",
	},
	{
		id: "gpt-4o-mini-transcribe",
		displayName: "GPT-4o Mini Transcribe",
		apiName: "gpt-4o-mini-transcribe",
		provider: "OpenAI",
		modality: "speech-to-text",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Budget STT: $0.003/min. Cost-efficient transcription for high-volume applications.",
	},
	{
		id: "whisper-1",
		displayName: "Whisper",
		apiName: "whisper-1",
		provider: "OpenAI",
		modality: "speech-to-text",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Open-source-derived STT: $0.006/min. 99+ languages, word-level timestamps supported.",
	},
	{
		id: "tts-1",
		displayName: "TTS Standard",
		apiName: "tts-1",
		provider: "OpenAI",
		modality: "text-to-speech",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Standard TTS: $15/1M characters. 13 voices, low latency, good quality for most apps.",
	},
	{
		id: "tts-1-hd",
		displayName: "TTS HD",
		apiName: "tts-1-hd",
		provider: "OpenAI",
		modality: "text-to-speech",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "HD TTS: $30/1M characters. Highest fidelity for professional audiobooks and narration.",
	},
	{
		id: "gpt-4o-mini-tts",
		displayName: "GPT-4o Mini TTS",
		apiName: "gpt-4o-mini-tts",
		provider: "OpenAI",
		modality: "text-to-speech",
		inputPricePer1M: 0.6,
		outputPricePer1M: 12.0,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Instructable TTS: $0.60/1M text input + $12/1M audio output tokens. Natural-language tone control.",
	},
	{
		id: "gemini-2-5-flash-tts",
		displayName: "Gemini 2.5 Flash TTS",
		apiName: "gemini-2.5-flash-tts",
		provider: "Google",
		modality: "text-to-speech",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Optimized TTS for price-performance and low-latency controllable speech generation.",
	},
	{
		id: "gemini-2-5-pro-tts",
		displayName: "Gemini 2.5 Pro TTS",
		apiName: "gemini-2.5-pro-tts",
		provider: "Google",
		modality: "text-to-speech",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Pro TTS for natural, steerable speech generation with low latency.",
	},
	{
		id: "chirp-2",
		displayName: "Google Chirp 2",
		apiName: "chirp_2",
		provider: "Google",
		modality: "speech-to-text",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Best-in-class batch STT (11.6% WER); 100+ languages. Batch-only, no streaming.",
	},
	{
		id: "deepgram-nova-3",
		displayName: "Deepgram Nova-3",
		apiName: "nova-3",
		provider: "Deepgram",
		modality: "speech-to-text",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Leading STT for voice agents; sub-300ms latency, $0.0043/min, 7 languages.",
	},
	{
		id: "deepgram-flux",
		displayName: "Deepgram Flux",
		apiName: "flux",
		provider: "Deepgram",
		modality: "speech-to-text",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Conversational STT with integrated end-of-turn detection (~260ms); purpose-built for voice agents.",
	},
	{
		id: "deepgram-aura-2",
		displayName: "Deepgram Aura-2",
		apiName: "aura-2",
		provider: "Deepgram",
		modality: "text-to-speech",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Low-latency TTS: 90ms TTFB, $0.000003/char (~$3/1M chars). Domain-specific pronunciation for healthcare/finance.",
	},
	{
		id: "assemblyai-universal-2",
		displayName: "AssemblyAI Universal-2",
		apiName: "universal-2",
		provider: "AssemblyAI",
		modality: "speech-to-text",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Best streaming STT accuracy (14.5% WER); $0.0025/min. Built-in sentiment, speaker diarization.",
	},
	{
		id: "assemblyai-slam-1",
		displayName: "AssemblyAI Slam-1",
		apiName: "slam-1",
		provider: "AssemblyAI",
		modality: "speech-to-text",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "LLM-based ASR; prompt-based domain customization, 1000+ custom terms. English only.",
	},
	{
		id: "elevenlabs-scribe-v2",
		displayName: "ElevenLabs Scribe v2",
		apiName: "scribe_v2",
		provider: "ElevenLabs",
		modality: "speech-to-text",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "High-accuracy multilingual STT; Scribe v2 RT achieves <150ms streaming latency, 70+ languages.",
	},
	{
		id: "elevenlabs-flash-v2-5",
		displayName: "ElevenLabs Flash v2.5",
		apiName: "eleven_flash_v2_5",
		provider: "ElevenLabs",
		modality: "text-to-speech",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Ultra-low-latency TTS (~75ms TTFB); 3,000+ voices, 29 languages. Best for real-time voice agents.",
	},
	{
		id: "elevenlabs-multilingual-v2",
		displayName: "ElevenLabs Multilingual v2",
		apiName: "eleven_multilingual_v2",
		provider: "ElevenLabs",
		modality: "text-to-speech",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Expressive studio-quality TTS; voice cloning, 29 languages. Best for audiobooks and narration.",
	},
	{
		id: "voxtral-small",
		displayName: "Voxtral Small",
		apiName: "voxtral-small-2507",
		provider: "Mistral",
		modality: "speech-to-text",
		inputPricePer1M: 0.1,
		outputPricePer1M: 0.3,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Mistral's first audio input model; instruct use cases with multilingual audio support.",
	},
	{
		id: "gpt-image-1-5",
		displayName: "GPT Image 1.5",
		apiName: "gpt-image-1.5",
		provider: "OpenAI",
		modality: "image-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "OpenAI's current image flagship; $0.009 (low) to $0.17 (high) per 1024x1024 image. Best prompt adherence.",
	},
	{
		id: "gpt-image-1",
		displayName: "GPT Image 1",
		apiName: "gpt-image-1",
		provider: "OpenAI",
		modality: "image-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Previous OpenAI image flagship; $0.011 (low) to $0.25 (high) per 1024x1024 image.",
	},
	{
		id: "gpt-image-1-mini",
		displayName: "GPT Image 1 Mini",
		apiName: "gpt-image-1-mini",
		provider: "OpenAI",
		modality: "image-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Budget image model; $0.005 (low) to $0.052 (high) per image. 85-90% of flagship quality.",
	},
	{
		id: "dall-e-3",
		displayName: "DALL-E 3",
		apiName: "dall-e-3",
		provider: "OpenAI",
		modality: "image-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Reliable legacy image model; $0.04 (standard) / $0.08 (HD) per 1024x1024. Strictest content filters.",
	},
	{
		id: "imagen-4",
		displayName: "Imagen 4 Standard",
		apiName: "imagen-4.0-generate-001",
		provider: "Google",
		modality: "image-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Google's flagship image model; $0.04/image standard, $0.06/image ultra. Transparent AI watermarking.",
	},
	{
		id: "imagen-4-fast",
		displayName: "Imagen 4 Fast",
		apiName: "imagen-4.0-fast-generate-001",
		provider: "Google",
		modality: "image-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Budget image generation at $0.02/image; best value among major cloud providers.",
	},
	{
		id: "flux-2-pro",
		displayName: "FLUX.2 Pro",
		apiName: "black-forest-labs/flux-2-pro",
		provider: "Black Forest Labs",
		modality: "image-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Top-ranked open image model; $0.03/image (1MP). Photorealistic, strong text rendering.",
	},
	{
		id: "flux-1-kontext-pro",
		displayName: "FLUX.1 Kontext Pro",
		apiName: "black-forest-labs/flux-1-kontext-pro",
		provider: "Black Forest Labs",
		modality: "image-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Context-aware image generation; accepts reference images. $0.04/image. Same price as FLUX 1.1 Pro.",
	},
	{
		id: "stable-diffusion-3-5",
		displayName: "Stable Diffusion 3.5",
		apiName: "stability/stable-diffusion-3-5-large",
		provider: "Stability AI",
		modality: "image-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Open-weight image model; $0.025-$0.05/image via API, free self-hosted. High customization.",
	},
	{
		id: "grok-imagine",
		displayName: "Grok Imagine",
		apiName: "grok-imagine",
		provider: "xAI",
		modality: "image-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "xAI's image model; $0.02/image standard, $0.07/image pro. Flat per-image pricing.",
	},
	{
		id: "veo-3-1",
		displayName: "Veo 3.1",
		apiName: "veo-3.1",
		provider: "Google",
		modality: "video-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Google's flagship video model; native audio-video, 4K@60fps. API ~$0.15/sec. Feb 2026.",
	},
	{
		id: "runway-gen-4-5",
		displayName: "Runway Gen-4.5",
		apiName: "gen4_5",
		provider: "Runway",
		modality: "video-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "#1 benchmark score for video; motion brushes, scene consistency. Plans from $12/month.",
	},
	{
		id: "kling-3-0",
		displayName: "Kling 3.0",
		apiName: "kling-3.0",
		provider: "Kuaishou",
		modality: "video-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "High-volume video generation leader; native audio, 4K, 2-min clips, ~$0.50/clip. API + free tier.",
	},
	{
		id: "luma-ray3",
		displayName: "Luma Ray3",
		apiName: "ray3",
		provider: "Luma AI",
		modality: "video-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "4K HDR video with superior physics simulation. From $7.99/mo. Strong for cinematic realism.",
	},
	{
		id: "pika-2-5",
		displayName: "Pika 2.5",
		apiName: "pika-2.5",
		provider: "Pika Labs",
		modality: "video-generation",
		inputPricePer1M: null,
		outputPricePer1M: null,
		cachedInputPricePer1M: null,
		contextLength: null,
		supportsTemperature: false,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Fast 42s renders with Pikaswaps and Pikaffects. From $8/mo. Best for social media content.",
	},
	{
		id: "gemini-2-5-flash-live",
		displayName: "Gemini 2.5 Flash Live",
		apiName: "gemini-2.5-flash-preview",
		provider: "Google",
		modality: "realtime-audio",
		inputPricePer1M: 0.3,
		outputPricePer1M: 2.5,
		cachedInputPricePer1M: null,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Gemini Live API for real-time multimodal interaction; low-latency voice and video streaming.",
	},
	{
		id: "mixtral-8x7b",
		displayName: "Mixtral 8x7B",
		apiName: "mistralai/mixtral-8x7b-instruct",
		provider: "Mistral",
		modality: "text",
		inputPricePer1M: 0.45,
		outputPricePer1M: 0.7,
		cachedInputPricePer1M: null,
		contextLength: 32000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Open-weight MoE model; strong multilingual reasoning, Apache 2.0 licensed.",
	},
	{
		id: "llama-3-2-11b",
		displayName: "Llama 3.2 11B Vision",
		apiName: "meta-llama/llama-3.2-11b-vision-instruct",
		provider: "Meta",
		modality: "multimodal",
		inputPricePer1M: 0.18,
		outputPricePer1M: 0.18,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: false,
		description: "Compact open multimodal model; edge-deployable with vision capabilities.",
	},
	{
		id: "llama-3-1-8b",
		displayName: "Llama 3.1 8B",
		apiName: "meta-llama/llama-3.1-8b-instruct",
		provider: "Meta",
		modality: "text",
		inputPricePer1M: 0.06,
		outputPricePer1M: 0.06,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Smallest production Llama; ultra-fast inference on Groq, ideal for simple tasks.",
	},
	{
		id: "gemma-4-31b",
		displayName: "Gemma 4 31B",
		apiName: "google/gemma-4-31b-it",
		provider: "Google",
		modality: "multimodal",
		inputPricePer1M: 0.1,
		outputPricePer1M: 0.3,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: true,
		supportsFunctionCalling: true,
		description: "Open-weight multimodal Gemma; state-of-the-art open-source vision and text model.",
	},
	{
		id: "ibm-granite-3-2-8b",
		displayName: "IBM Granite 3.2 8B",
		apiName: "ibm/granite-3.2-8b-instruct",
		provider: "IBM",
		modality: "text",
		inputPricePer1M: 0.05,
		outputPricePer1M: 0.15,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Enterprise open-source model; Apache 2.0, strong on structured tasks and RAG.",
	},
	{
		id: "ministral-8b",
		displayName: "Ministral 8B",
		apiName: "ministral-8b-latest",
		provider: "Mistral",
		modality: "text",
		inputPricePer1M: 0.1,
		outputPricePer1M: 0.1,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Ultra-efficient edge model; best-in-class for its parameter size.",
	},
	{
		id: "ministral-3b",
		displayName: "Ministral 3B",
		apiName: "ministral-3b-latest",
		provider: "Mistral",
		modality: "text",
		inputPricePer1M: 0.04,
		outputPricePer1M: 0.04,
		cachedInputPricePer1M: null,
		contextLength: 128000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Smallest Mistral model; on-device and edge AI deployment.",
	},
	{
		id: "minimax-m2-7",
		displayName: "MiniMax M2.7",
		apiName: "minimax/minimax-m2.7",
		provider: "MiniMax",
		modality: "text",
		inputPricePer1M: 0.3,
		outputPricePer1M: 1.5,
		cachedInputPricePer1M: null,
		contextLength: 1000000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Chinese frontier model; competitive pricing with 1M context window.",
	},
	{
		id: "kimi-k2-5",
		displayName: "Kimi K2.5",
		apiName: "moonshot-ai/kimi-k2-5",
		provider: "Moonshot AI",
		modality: "text",
		inputPricePer1M: 0.6,
		outputPricePer1M: 2.5,
		cachedInputPricePer1M: null,
		contextLength: 200000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: true,
		description: "Moonshot's latest model; strong coding and long context capabilities.",
	},
	{
		id: "perplexity-sonar",
		displayName: "Perplexity Sonar",
		apiName: "sonar",
		provider: "Perplexity",
		modality: "text",
		inputPricePer1M: 1.0,
		outputPricePer1M: 1.0,
		cachedInputPricePer1M: null,
		contextLength: 127000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Search-grounded LLM; real-time web results baked in. $5/1K API requests.",
	},
	{
		id: "perplexity-sonar-pro",
		displayName: "Perplexity Sonar Pro",
		apiName: "sonar-pro",
		provider: "Perplexity",
		modality: "text",
		inputPricePer1M: 3.0,
		outputPricePer1M: 15.0,
		cachedInputPricePer1M: null,
		contextLength: 200000,
		supportsTemperature: true,
		supportsTopK: false,
		supportsFunctionCalling: false,
		description: "Advanced search-grounded model with deeper web reasoning and citations.",
	},
];

// LLM text/multimodal models only — for calculator dropdown
export const LLM_MODELS = MODEL_PRICING.filter((m) => (m.modality === "text" || m.modality === "multimodal") && !!m.inputPricePer1M);

export interface CalculatorConfig {
	taskType: "voice-call" | "chatbot" | "crm" | "image-generation" | "video-generation" | "custom";
	aiComponents: ("llm" | "stt" | "tts" | "streaming")[];
	modelId: string;
	systemPromptChars: number;
	avgUserInputChars: number;
	avgResponseChars: number;
	conversationTurns: number;
	toolCallsPerConversation: number;
	toolDescriptionChars: number;
	avgCallDurationMinutes: number;
	wordsPerMinute: number;
	realtimeMode: boolean;
	reasoningMultiplier: number;
	usePromptCaching: boolean;
	includeHistoryGrowth: boolean;
	monthlyUsers: number;
	sttModelId: string;
	ttsModelId: string;
	// Image / video
	imageModelId: string;
	imagesPerConversation: number;
	videoModelId: string;
	videoSecondsPerConversation: number;
}

export const DEFAULT_CONFIG: CalculatorConfig = {
	taskType: "chatbot",
	aiComponents: ["llm"],
	modelId: "gpt-4o-mini",
	systemPromptChars: 500,
	avgUserInputChars: 200,
	avgResponseChars: 400,
	conversationTurns: 5,
	toolCallsPerConversation: 2,
	toolDescriptionChars: 300,
	avgCallDurationMinutes: 3,
	wordsPerMinute: 150,
	realtimeMode: false,
	reasoningMultiplier: 1.0,
	usePromptCaching: false,
	includeHistoryGrowth: false,
	monthlyUsers: 1000,
	sttModelId: "whisper-1",
	ttsModelId: "tts-1",
	imageModelId: "dall-e-3",
	imagesPerConversation: 1,
	videoModelId: "gen-4-turbo",
	videoSecondsPerConversation: 5,
};

export interface Preset {
	id: string;
	name: string;
	description: string;
	config: Partial<CalculatorConfig>;
}

export const PRESETS: Preset[] = [
	{
		id: "whatsapp-bot",
		name: "WhatsApp Bot",
		description: "Simple customer support chatbot",
		config: {
			taskType: "chatbot",
			aiComponents: ["llm"],
			modelId: "gpt-4o-mini",
			systemPromptChars: 800,
			avgUserInputChars: 120,
			avgResponseChars: 250,
			conversationTurns: 4,
			toolCallsPerConversation: 0,
			toolDescriptionChars: 0,
			reasoningMultiplier: 1.0,
			usePromptCaching: true,
			includeHistoryGrowth: true,
			monthlyUsers: 5000,
		},
	},
	{
		id: "ai-voice-agent",
		name: "AI Voice Agent",
		description: "Inbound voice call handler with STT + LLM + TTS",
		config: {
			taskType: "voice-call",
			aiComponents: ["llm", "stt", "tts"],
			modelId: "gpt-4o",
			systemPromptChars: 1200,
			avgUserInputChars: 80,
			avgResponseChars: 150,
			conversationTurns: 8,
			toolCallsPerConversation: 3,
			toolDescriptionChars: 400,
			avgCallDurationMinutes: 5,
			wordsPerMinute: 140,
			reasoningMultiplier: 1.0,
			usePromptCaching: true,
			includeHistoryGrowth: true,
			monthlyUsers: 2000,
		},
	},
	{
		id: "crm-automation",
		name: "CRM Automation",
		description: "AI-driven CRM data enrichment & classification",
		config: {
			taskType: "crm",
			aiComponents: ["llm"],
			modelId: "claude-3-5-haiku",
			systemPromptChars: 1500,
			avgUserInputChars: 600,
			avgResponseChars: 200,
			conversationTurns: 1,
			toolCallsPerConversation: 5,
			toolDescriptionChars: 800,
			reasoningMultiplier: 1.0,
			usePromptCaching: true,
			includeHistoryGrowth: false,
			monthlyUsers: 10000,
		},
	},
	{
		id: "reasoning-agent",
		name: "Reasoning Agent",
		description: "Complex multi-step reasoning with o1/o3 models",
		config: {
			taskType: "custom",
			aiComponents: ["llm"],
			modelId: "o3-mini",
			systemPromptChars: 2000,
			avgUserInputChars: 500,
			avgResponseChars: 1000,
			conversationTurns: 3,
			toolCallsPerConversation: 4,
			toolDescriptionChars: 600,
			reasoningMultiplier: 2.5,
			usePromptCaching: false,
			includeHistoryGrowth: false,
			monthlyUsers: 500,
		},
	},
];
