// ─────────────────────────────────────────────────────────────────────────────
// Model data — source of truth for all pricing and capability information.
//
// HOW TO ADD A NEW PROVIDER / MODEL:
//   1. Add a new object to MODEL_PRICING below.
//   2. Use any string for `provider` — filters derive it dynamically.
//   3. Use one of the Modality values for `modality`.
//   4. That's it. No other files need editing.
// ─────────────────────────────────────────────────────────────────────────────

export type Modality = 'text' | 'multimodal' | 'audio' | 'image' | 'video'

// Provider is intentionally a plain string so any new provider can be added
// without touching this type. The union below is kept only for documentation.
export type Provider = string

export interface ModelPricing {
  id: string
  displayName: string
  apiName: string
  provider: Provider
  modality: Modality
  // Token pricing (text / multimodal LLMs)
  inputPricePer1M: number        // $ per 1M input tokens  (0 if not applicable)
  outputPricePer1M: number       // $ per 1M output tokens (0 if not applicable)
  cachedInputPricePer1M?: number | null
  contextLength: number          // tokens (0 if not applicable)
  // Capabilities
  supportsTemperature: boolean
  supportsTopK: boolean
  supportsFunctionCalling: boolean
  // Audio pricing
  sttPricePer1Min?: number        // $ per minute  (STT)
  ttsPricePer1KChars?: number     // $ per 1K chars (TTS)
  // Image pricing
  imagePricePerImage?: number     // $ per image generated
  imageResolution?: string        // e.g. "1024×1024"
  // Video pricing
  videoPricePerSecond?: number    // $ per second of video
  videoResolution?: string        // e.g. "720p"
  // Meta
  description?: string
}

// ── Helper types derived from the data ───────────────────────────────────────
export type DefaultConfig = {
  modelId: string
  taskType: TaskType
  aiComponents: AIComponent[]
  systemPromptTokens: number
  userPromptTokens: number
  assistantResponseTokens: number
  conversationHistory: number
  historyGrowthRate: number
  enablePromptCaching: boolean
  reasoningMultiplier: number
  audioInputMinutes: number
  audioOutputMinutes: number
  sttModelId: string
  ttsModelId: string
  monthlyUsers: number
  imageModelId: string
  videoModelId: string
  imagesPerConversation: number
  videoSecondsPerConversation: number
}

export type TaskType =
  | 'voice-call'
  | 'chatbot'
  | 'crm'
  | 'image-generation'
  | 'video-generation'
  | 'custom'

export type AIComponent = 'llm' | 'stt' | 'tts' | 'streaming'

export interface CalculatorConfig {
  taskType: TaskType
  aiComponents: AIComponent[]
  modelId: string
  systemPromptTokens: number
  userPromptTokens: number
  assistantResponseTokens: number
  conversationHistory: number
  historyGrowthRate: number
  enablePromptCaching: boolean
  reasoningMultiplier: number
  audioInputMinutes: number
  audioOutputMinutes: number
  sttModelId: string
  ttsModelId: string
  monthlyUsers: number
  // Image / video
  imageModelId: string
  videoModelId: string
  imagesPerConversation: number
  videoSecondsPerConversation: number
}

export const DEFAULT_CONFIG: CalculatorConfig = {
  taskType: 'chatbot',
  aiComponents: ['llm'],
  modelId: 'gpt-4o-mini',
  systemPromptTokens: 500,
  userPromptTokens: 150,
  assistantResponseTokens: 300,
  conversationHistory: 5,
  historyGrowthRate: 0,
  enablePromptCaching: false,
  reasoningMultiplier: 1,
  audioInputMinutes: 2,
  audioOutputMinutes: 2,
  sttModelId: 'whisper-1',
  ttsModelId: 'tts-1',
  monthlyUsers: 1000,
  imageModelId: 'dall-e-3',
  videoModelId: 'runway-gen3-alpha-turbo',
  imagesPerConversation: 1,
  videoSecondsPerConversation: 5,
}

// ── Model Pricing Data ────────────────────────────────────────────────────────
export const MODEL_PRICING: ModelPricing[] = [
  // ── OpenAI — Text / Multimodal ──────────────────────────────────────────
  {
    id: 'gpt-4o',
    displayName: 'GPT-4o',
    apiName: 'gpt-4o',
    provider: 'OpenAI',
    modality: 'multimodal',
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    cachedInputPricePer1M: 1.25,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Flagship multimodal model with vision, audio, and text capabilities.',
  },
  {
    id: 'gpt-4o-mini',
    displayName: 'GPT-4o Mini',
    apiName: 'gpt-4o-mini',
    provider: 'OpenAI',
    modality: 'multimodal',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    cachedInputPricePer1M: 0.075,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Cost-efficient small multimodal model, strong for high-volume tasks.',
  },
  {
    id: 'gpt-4.1',
    displayName: 'GPT-4.1',
    apiName: 'gpt-4.1',
    provider: 'OpenAI',
    modality: 'multimodal',
    inputPricePer1M: 2.0,
    outputPricePer1M: 8.0,
    cachedInputPricePer1M: 0.5,
    contextLength: 1000000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Instruction-following powerhouse with 1M context; excellent for agentic workflows.',
  },
  {
    id: 'gpt-4.1-mini',
    displayName: 'GPT-4.1 Mini',
    apiName: 'gpt-4.1-mini',
    provider: 'OpenAI',
    modality: 'multimodal',
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    cachedInputPricePer1M: 0.1,
    contextLength: 1000000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Affordable GPT-4.1-class model with 1M context for high-volume tasks.',
  },
  {
    id: 'gpt-4.1-nano',
    displayName: 'GPT-4.1 Nano',
    apiName: 'gpt-4.1-nano',
    provider: 'OpenAI',
    modality: 'text',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    cachedInputPricePer1M: 0.025,
    contextLength: 1000000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Ultra-cheap nano model for simple high-volume classification and extraction.',
  },
  {
    id: 'o3',
    displayName: 'o3',
    apiName: 'o3',
    provider: 'OpenAI',
    modality: 'text',
    inputPricePer1M: 10.0,
    outputPricePer1M: 40.0,
    cachedInputPricePer1M: 2.5,
    contextLength: 200000,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: "OpenAI's most powerful reasoning model; excels at math, coding, and science.",
  },
  {
    id: 'o3-mini',
    displayName: 'o3-mini',
    apiName: 'o3-mini',
    provider: 'OpenAI',
    modality: 'text',
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    cachedInputPricePer1M: 0.55,
    contextLength: 200000,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Compact reasoning model optimized for cost-efficient STEM tasks.',
  },
  {
    id: 'o4-mini',
    displayName: 'o4-mini',
    apiName: 'o4-mini',
    provider: 'OpenAI',
    modality: 'multimodal',
    inputPricePer1M: 1.1,
    outputPricePer1M: 4.4,
    cachedInputPricePer1M: 0.275,
    contextLength: 200000,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Efficient reasoning model with vision; strong on coding, math, and visual tasks.',
  },
  {
    id: 'o1',
    displayName: 'o1',
    apiName: 'o1',
    provider: 'OpenAI',
    modality: 'text',
    inputPricePer1M: 15.0,
    outputPricePer1M: 60.0,
    cachedInputPricePer1M: 7.5,
    contextLength: 200000,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Original advanced reasoning model; thorough chain-of-thought inference.',
  },
  // ── OpenAI — Audio ──────────────────────────────────────────────────────
  {
    id: 'whisper-1',
    displayName: 'Whisper',
    apiName: 'whisper-1',
    provider: 'OpenAI',
    modality: 'audio',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    sttPricePer1Min: 0.006,
    description: 'Industry-standard speech-to-text model; supports 100+ languages.',
  },
  {
    id: 'tts-1',
    displayName: 'TTS-1',
    apiName: 'tts-1',
    provider: 'OpenAI',
    modality: 'audio',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    ttsPricePer1KChars: 0.015,
    description: 'Standard text-to-speech model; low latency, 6 voice options.',
  },
  {
    id: 'tts-1-hd',
    displayName: 'TTS-1 HD',
    apiName: 'tts-1-hd',
    provider: 'OpenAI',
    modality: 'audio',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    ttsPricePer1KChars: 0.03,
    description: 'High-definition TTS; optimized for audio quality over latency.',
  },
  // ── OpenAI — Image ──────────────────────────────────────────────────────
  {
    id: 'dall-e-3',
    displayName: 'DALL-E 3',
    apiName: 'dall-e-3',
    provider: 'OpenAI',
    modality: 'image',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    imagePricePerImage: 0.04,
    imageResolution: '1024×1024',
    description: 'Latest DALL-E; photorealistic images with strong prompt adherence.',
  },
  {
    id: 'gpt-image-1',
    displayName: 'GPT Image 1',
    apiName: 'gpt-image-1',
    provider: 'OpenAI',
    modality: 'image',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    imagePricePerImage: 0.167,
    imageResolution: '1024×1024',
    description: "OpenAI's newest image model with world-class instruction following.",
  },
  // ── Anthropic ───────────────────────────────────────────────────────────
  {
    id: 'claude-opus-4-6',
    displayName: 'Claude Opus 4.6',
    apiName: 'claude-opus-4-6',
    provider: 'Anthropic',
    modality: 'multimodal',
    inputPricePer1M: 5.0,
    outputPricePer1M: 25.0,
    cachedInputPricePer1M: 0.5,
    contextLength: 1000000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: "Anthropic's most capable model; frontier reasoning, coding, and enterprise agentic tasks.",
  },
  {
    id: 'claude-sonnet-4-6',
    displayName: 'Claude Sonnet 4.6',
    apiName: 'claude-sonnet-4-6',
    provider: 'Anthropic',
    modality: 'multimodal',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    cachedInputPricePer1M: 0.3,
    contextLength: 1000000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Best balance of intelligence and cost; high-throughput developer favorite with 1M context.',
  },
  {
    id: 'claude-haiku-4-5',
    displayName: 'Claude Haiku 4.5',
    apiName: 'claude-haiku-4-5-20251001',
    provider: 'Anthropic',
    modality: 'multimodal',
    inputPricePer1M: 1.0,
    outputPricePer1M: 5.0,
    cachedInputPricePer1M: 0.1,
    contextLength: 200000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Fastest and most affordable Claude; ideal for speed-critical high-volume workloads.',
  },
  {
    id: 'claude-3-5-sonnet',
    displayName: 'Claude 3.5 Sonnet',
    apiName: 'claude-3-5-sonnet-20241022',
    provider: 'Anthropic',
    modality: 'multimodal',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    cachedInputPricePer1M: 0.3,
    contextLength: 200000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Highly capable vision and text model; prior workhorse for production apps.',
  },
  {
    id: 'claude-3-haiku',
    displayName: 'Claude 3 Haiku',
    apiName: 'claude-3-haiku-20240307',
    provider: 'Anthropic',
    modality: 'multimodal',
    inputPricePer1M: 0.25,
    outputPricePer1M: 1.25,
    cachedInputPricePer1M: 0.03,
    contextLength: 200000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Legacy lightweight model; still popular for low-cost classification tasks.',
  },
  // ── Google ──────────────────────────────────────────────────────────────
  {
    id: 'gemini-2-5-pro',
    displayName: 'Gemini 2.5 Pro',
    apiName: 'gemini-2.5-pro',
    provider: 'Google',
    modality: 'multimodal',
    inputPricePer1M: 1.25,
    outputPricePer1M: 10.0,
    cachedInputPricePer1M: 0.31,
    contextLength: 1000000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Production-ready Google flagship; strong reasoning, coding, and analysis.',
  },
  {
    id: 'gemini-2-5-flash',
    displayName: 'Gemini 2.5 Flash',
    apiName: 'gemini-2.5-flash',
    provider: 'Google',
    modality: 'multimodal',
    inputPricePer1M: 0.3,
    outputPricePer1M: 2.5,
    cachedInputPricePer1M: 0.075,
    contextLength: 1000000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Best value Google model; fast, affordable, supports thinking mode.',
  },
  {
    id: 'gemini-2-5-flash-lite',
    displayName: 'Gemini 2.5 Flash-Lite',
    apiName: 'gemini-2.5-flash-lite',
    provider: 'Google',
    modality: 'multimodal',
    inputPricePer1M: 0.1,
    outputPricePer1M: 0.4,
    cachedInputPricePer1M: 0.025,
    contextLength: 1000000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Cheapest production Gemini model; ideal for high-volume simple tasks.',
  },
  {
    id: 'gemini-3-flash',
    displayName: 'Gemini 3 Flash',
    apiName: 'gemini-3.0-flash',
    provider: 'Google',
    modality: 'multimodal',
    inputPricePer1M: 0.5,
    outputPricePer1M: 3.0,
    cachedInputPricePer1M: 0.125,
    contextLength: 1000000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Balanced speed and capability; native multimodal with audio generation.',
  },
  {
    id: 'gemini-3-1-pro',
    displayName: 'Gemini 3.1 Pro',
    apiName: 'gemini-3.1-pro-preview',
    provider: 'Google',
    modality: 'multimodal',
    inputPricePer1M: 2.0,
    outputPricePer1M: 12.0,
    cachedInputPricePer1M: 0.5,
    contextLength: 1000000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: "Google's latest flagship reasoning model; frontier intelligence with superior search.",
  },
  // ── Meta ────────────────────────────────────────────────────────────────
  {
    id: 'llama-4-maverick',
    displayName: 'Llama 4 Maverick',
    apiName: 'meta-llama/llama-4-maverick',
    provider: 'Meta',
    modality: 'multimodal',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    cachedInputPricePer1M: 0.075,
    contextLength: 1000000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: "Meta's flagship open model; 400B MoE, multimodal, 1M context.",
  },
  {
    id: 'llama-4-scout',
    displayName: 'Llama 4 Scout',
    apiName: 'meta-llama/llama-4-scout',
    provider: 'Meta',
    modality: 'multimodal',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    cachedInputPricePer1M: 0.075,
    contextLength: 10000000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Long-context specialist; world-record 10M token window, single-GPU deployable.',
  },
  {
    id: 'llama-3-3-70b',
    displayName: 'Llama 3.3 70B',
    apiName: 'meta-llama/llama-3.3-70b-instruct',
    provider: 'Meta',
    modality: 'text',
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.35,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Highly capable open-source model; near GPT-4o quality at a fraction of the cost.',
  },
  {
    id: 'llama-3-1-405b',
    displayName: 'Llama 3.1 405B',
    apiName: 'meta-llama/llama-3.1-405b-instruct',
    provider: 'Meta',
    modality: 'text',
    inputPricePer1M: 3.5,
    outputPricePer1M: 3.5,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Largest open Llama; GPT-4-class performance with open weights for self-hosting.',
  },
  // ── Mistral AI ──────────────────────────────────────────────────────────
  {
    id: 'mistral-large-3',
    displayName: 'Mistral Large 3',
    apiName: 'mistral-large-2512',
    provider: 'Mistral AI',
    modality: 'text',
    inputPricePer1M: 0.5,
    outputPricePer1M: 1.5,
    contextLength: 262000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: "Mistral's flagship model; strong multilingual reasoning and long context.",
  },
  {
    id: 'mistral-medium-3',
    displayName: 'Mistral Medium 3',
    apiName: 'mistral-medium-3',
    provider: 'Mistral AI',
    modality: 'multimodal',
    inputPricePer1M: 0.4,
    outputPricePer1M: 2.0,
    contextLength: 131000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Versatile mid-tier model with vision capabilities.',
  },
  {
    id: 'mistral-small-3-1',
    displayName: 'Mistral Small 3.1',
    apiName: 'mistral-small-latest',
    provider: 'Mistral AI',
    modality: 'multimodal',
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.6,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Budget-friendly Mistral model; great price-to-performance for most tasks.',
  },
  {
    id: 'mistral-nemo',
    displayName: 'Mistral NeMo',
    apiName: 'open-mistral-nemo',
    provider: 'Mistral AI',
    modality: 'text',
    inputPricePer1M: 0.02,
    outputPricePer1M: 0.04,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Cheapest commercial LLM option; multilingual, open-weight, Apache 2.0.',
  },
  {
    id: 'codestral-2508',
    displayName: 'Codestral 2508',
    apiName: 'codestral-2508',
    provider: 'Mistral AI',
    modality: 'text',
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.9,
    contextLength: 256000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Coding specialist; 256K context, fill-in-the-middle support.',
  },
  {
    id: 'magistral-medium',
    displayName: 'Magistral Medium',
    apiName: 'magistral-medium-latest',
    provider: 'Mistral AI',
    modality: 'text',
    inputPricePer1M: 0.4,
    outputPricePer1M: 2.0,
    contextLength: 128000,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: "Mistral's reasoning model; hybrid instruct, reasoning, and coding.",
  },
  {
    id: 'pixtral-large',
    displayName: 'Pixtral Large',
    apiName: 'pixtral-large-latest',
    provider: 'Mistral AI',
    modality: 'multimodal',
    inputPricePer1M: 2.0,
    outputPricePer1M: 6.0,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: "Mistral's frontier multimodal model; best-in-class text and vision.",
  },
  // ── xAI ─────────────────────────────────────────────────────────────────
  {
    id: 'grok-3',
    displayName: 'Grok 3',
    apiName: 'grok-3',
    provider: 'xAI',
    modality: 'text',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    cachedInputPricePer1M: 0.75,
    contextLength: 131072,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: "xAI's most capable model; excels at reasoning, math, and coding tasks.",
  },
  {
    id: 'grok-3-mini',
    displayName: 'Grok 3 Mini',
    apiName: 'grok-3-mini',
    provider: 'xAI',
    modality: 'text',
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.5,
    cachedInputPricePer1M: 0.075,
    contextLength: 131072,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Lightweight reasoning model from xAI; fast and cost-efficient.',
  },
  {
    id: 'grok-2-vision',
    displayName: 'Grok 2 Vision',
    apiName: 'grok-2-vision-1212',
    provider: 'xAI',
    modality: 'multimodal',
    inputPricePer1M: 2.0,
    outputPricePer1M: 10.0,
    contextLength: 32768,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Multimodal Grok model with image understanding capabilities.',
  },
  // ── DeepSeek ────────────────────────────────────────────────────────────
  {
    id: 'deepseek-v4',
    displayName: 'DeepSeek V4',
    apiName: 'deepseek-chat',
    provider: 'DeepSeek',
    modality: 'text',
    inputPricePer1M: 0.3,
    outputPricePer1M: 0.5,
    cachedInputPricePer1M: 0.03,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: "DeepSeek's latest flagship; 81% SWE-bench, best value frontier model.",
  },
  {
    id: 'deepseek-r1',
    displayName: 'DeepSeek R1',
    apiName: 'deepseek-reasoner',
    provider: 'DeepSeek',
    modality: 'text',
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    cachedInputPricePer1M: 0.14,
    contextLength: 128000,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    description: 'Open-source reasoning model rivaling o1 at ~96% lower cost.',
  },
  {
    id: 'deepseek-v3',
    displayName: 'DeepSeek V3',
    apiName: 'deepseek-chat-v3',
    provider: 'DeepSeek',
    modality: 'text',
    inputPricePer1M: 0.28,
    outputPricePer1M: 0.42,
    cachedInputPricePer1M: 0.028,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Budget flagship with near-frontier quality; 671B MoE architecture.',
  },
  // ── Cohere ──────────────────────────────────────────────────────────────
  {
    id: 'command-r-plus',
    displayName: 'Command R+',
    apiName: 'command-r-plus',
    provider: 'Cohere',
    modality: 'text',
    inputPricePer1M: 2.5,
    outputPricePer1M: 10.0,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Enterprise RAG champion; optimized for grounded generation and tool use.',
  },
  {
    id: 'command-r',
    displayName: 'Command R',
    apiName: 'command-r',
    provider: 'Cohere',
    modality: 'text',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.6,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Efficient retrieval-augmented generation; strong multi-step tool use.',
  },
  {
    id: 'command-a',
    displayName: 'Command A',
    apiName: 'command-a-03-2025',
    provider: 'Cohere',
    modality: 'text',
    inputPricePer1M: 2.5,
    outputPricePer1M: 10.0,
    contextLength: 256000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: "Cohere's most powerful agentic model; 111B parameters, 256K context.",
  },
  // ── Amazon ──────────────────────────────────────────────────────────────
  {
    id: 'nova-pro',
    displayName: 'Nova Pro',
    apiName: 'amazon.nova-pro-v1:0',
    provider: 'Amazon',
    modality: 'multimodal',
    inputPricePer1M: 0.8,
    outputPricePer1M: 3.2,
    cachedInputPricePer1M: 0.2,
    contextLength: 300000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Amazon Nova flagship; strong multimodal understanding and tool use.',
  },
  {
    id: 'nova-lite',
    displayName: 'Nova Lite',
    apiName: 'amazon.nova-lite-v1:0',
    provider: 'Amazon',
    modality: 'multimodal',
    inputPricePer1M: 0.06,
    outputPricePer1M: 0.24,
    cachedInputPricePer1M: 0.015,
    contextLength: 300000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Ultra-low cost multimodal; exceptionally fast for high-volume tasks.',
  },
  {
    id: 'nova-micro',
    displayName: 'Nova Micro',
    apiName: 'amazon.nova-micro-v1:0',
    provider: 'Amazon',
    modality: 'text',
    inputPricePer1M: 0.035,
    outputPricePer1M: 0.14,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: "Amazon's cheapest text-only model; fastest latency in the Nova family.",
  },
  // ── ElevenLabs ──────────────────────────────────────────────────────────
  {
    id: 'elevenlabs-turbo-v2-5',
    displayName: 'Turbo v2.5',
    apiName: 'eleven_turbo_v2_5',
    provider: 'ElevenLabs',
    modality: 'audio',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    ttsPricePer1KChars: 0.008,
    description: 'Ultra-low latency TTS; sub-200ms for real-time voice applications.',
  },
  {
    id: 'elevenlabs-multilingual-v2',
    displayName: 'Multilingual v2',
    apiName: 'eleven_multilingual_v2',
    provider: 'ElevenLabs',
    modality: 'audio',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    ttsPricePer1KChars: 0.012,
    description: 'Flagship TTS with 29 language support; best-in-class voice cloning.',
  },
  // ── Deepgram ─────────────────────────────────────────────────────────────
  {
    id: 'deepgram-nova-3',
    displayName: 'Nova-3',
    apiName: 'nova-3',
    provider: 'Deepgram',
    modality: 'audio',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    sttPricePer1Min: 0.0043,
    description: 'Best-in-class real-time STT; 12% lower WER than Whisper at lower cost.',
  },
  {
    id: 'deepgram-nova-2',
    displayName: 'Nova-2',
    apiName: 'nova-2',
    provider: 'Deepgram',
    modality: 'audio',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    sttPricePer1Min: 0.0059,
    description: 'Production-grade STT with speaker diarization and smart formatting.',
  },
  {
    id: 'deepgram-whisper',
    displayName: 'Whisper (Deepgram)',
    apiName: 'whisper',
    provider: 'Deepgram',
    modality: 'audio',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    sttPricePer1Min: 0.0048,
    description: "OpenAI Whisper hosted on Deepgram's low-latency infrastructure.",
  },
  // ── Stability AI — Image ─────────────────────────────────────────────────
  {
    id: 'stable-image-ultra',
    displayName: 'Stable Image Ultra',
    apiName: 'stable-image-ultra',
    provider: 'Stability AI',
    modality: 'image',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    imagePricePerImage: 0.08,
    imageResolution: '1024×1024',
    description: 'Highest quality Stability image model; photorealistic and artistic outputs.',
  },
  {
    id: 'stable-image-core',
    displayName: 'Stable Image Core',
    apiName: 'stable-image-core',
    provider: 'Stability AI',
    modality: 'image',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    imagePricePerImage: 0.03,
    imageResolution: '1024×1024',
    description: 'Fast and affordable; ideal for rapid prototyping and creative workflows.',
  },
  {
    id: 'sd3-5-large',
    displayName: 'SD 3.5 Large',
    apiName: 'sd3.5-large',
    provider: 'Stability AI',
    modality: 'image',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    imagePricePerImage: 0.065,
    imageResolution: '1024×1024',
    description: 'Stable Diffusion 3.5 Large; improved typography and photorealism.',
  },
  // ── Runway — Video ───────────────────────────────────────────────────────
  {
    id: 'runway-gen3-alpha-turbo',
    displayName: 'Gen-3 Alpha Turbo',
    apiName: 'gen3a_turbo',
    provider: 'Runway',
    modality: 'video',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    videoPricePerSecond: 0.05,
    videoResolution: '1280×768',
    description: 'Fast text-to-video; 5s or 10s clips at 24fps.',
  },
  {
    id: 'runway-gen3-alpha',
    displayName: 'Gen-3 Alpha',
    apiName: 'gen3a',
    provider: 'Runway',
    modality: 'video',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    videoPricePerSecond: 0.1,
    videoResolution: '1280×768',
    description: 'Highest quality Runway model; cinematic realism and motion control.',
  },
  // ── Google — Image ───────────────────────────────────────────────────────
  {
    id: 'imagen-3',
    displayName: 'Imagen 3',
    apiName: 'imagen-3.0-generate-002',
    provider: 'Google',
    modality: 'image',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    imagePricePerImage: 0.04,
    imageResolution: '1024×1024',
    description: "Google's highest quality text-to-image model; photorealism and fine detail.",
  },
  // ── Google — Video ───────────────────────────────────────────────────────
  {
    id: 'veo-3',
    displayName: 'Veo 3',
    apiName: 'veo-3.0-generate-preview',
    provider: 'Google',
    modality: 'video',
    inputPricePer1M: 0,
    outputPricePer1M: 0,
    contextLength: 0,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    videoPricePerSecond: 0.35,
    videoResolution: '1080p',
    description: "Google's next-gen video model; audio-video synced generation up to 8s.",
  },
  // ── Groq (hosted inference) ──────────────────────────────────────────────
  {
    id: 'groq-llama-3-3-70b',
    displayName: 'Llama 3.3 70B (Groq)',
    apiName: 'llama-3.3-70b-versatile',
    provider: 'Groq',
    modality: 'text',
    inputPricePer1M: 0.59,
    outputPricePer1M: 0.79,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Llama 3.3 70B on Groq LPU; 275 tokens/sec — fastest available inference.',
  },
  {
    id: 'groq-llama-4-scout',
    displayName: 'Llama 4 Scout (Groq)',
    apiName: 'meta-llama/llama-4-scout-17b-16e-instruct',
    provider: 'Groq',
    modality: 'text',
    inputPricePer1M: 0.11,
    outputPricePer1M: 0.34,
    contextLength: 131072,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Meta Llama 4 Scout on Groq; ultra-fast inference for agentic tasks.',
  },
  {
    id: 'groq-gemma-2-9b',
    displayName: 'Gemma 2 9B (Groq)',
    apiName: 'gemma2-9b-it',
    provider: 'Groq',
    modality: 'text',
    inputPricePer1M: 0.2,
    outputPricePer1M: 0.2,
    contextLength: 8192,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: false,
    description: "Google's Gemma 2 9B on Groq hardware; great for lightweight chat apps.",
  },
  // ── Together AI ──────────────────────────────────────────────────────────
  {
    id: 'together-qwen-2-5-72b',
    displayName: 'Qwen 2.5 72B',
    apiName: 'Qwen/Qwen2.5-72B-Instruct-Turbo',
    provider: 'Together AI',
    modality: 'text',
    inputPricePer1M: 1.2,
    outputPricePer1M: 1.2,
    contextLength: 32768,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: "Alibaba's Qwen 2.5 72B on Together AI; strong multilingual and coding.",
  },
  {
    id: 'together-llama-3-1-8b',
    displayName: 'Llama 3.1 8B Turbo',
    apiName: 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo',
    provider: 'Together AI',
    modality: 'text',
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.18,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: true,
    supportsFunctionCalling: true,
    description: 'Fast Llama 3.1 8B on Together AI; best price for quick chat tasks.',
  },
  // ── Perplexity ───────────────────────────────────────────────────────────
  {
    id: 'perplexity-sonar-pro',
    displayName: 'Sonar Pro',
    apiName: 'sonar-pro',
    provider: 'Perplexity',
    modality: 'text',
    inputPricePer1M: 3.0,
    outputPricePer1M: 15.0,
    contextLength: 200000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: false,
    description: 'Online LLM with real-time web search; citations included, 200K context.',
  },
  {
    id: 'perplexity-sonar',
    displayName: 'Sonar',
    apiName: 'sonar',
    provider: 'Perplexity',
    modality: 'text',
    inputPricePer1M: 1.0,
    outputPricePer1M: 1.0,
    contextLength: 128000,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: false,
    description: 'Affordable online LLM; web-grounded answers with source citations.',
  },
  // ── Fireworks AI ─────────────────────────────────────────────────────────
  {
    id: 'fireworks-llama-3-1-405b',
    displayName: 'Llama 3.1 405B (Fireworks)',
    apiName: 'accounts/fireworks/models/llama-v3p1-405b-instruct',
    provider: 'Fireworks AI',
    modality: 'text',
    inputPricePer1M: 3.0,
    outputPricePer1M: 3.0,
    contextLength: 131072,
    supportsTemperature: true,
    supportsTopK: false,
    supportsFunctionCalling: true,
    description: 'Llama 3.1 405B at competitive pricing on Fireworks fast inference infra.',
  },
  {
    id: 'fireworks-deepseek-r1',
    displayName: 'DeepSeek R1 (Fireworks)',
    apiName: 'accounts/fireworks/models/deepseek-r1',
    provider: 'Fireworks AI',
    modality: 'text',
    inputPricePer1M: 0.8,
    outputPricePer1M: 0.8,
    contextLength: 160000,
    supportsTemperature: false,
    supportsTopK: false,
    supportsFunctionCalling: false,
    description: 'DeepSeek R1 on Fireworks; fast reasoning inference with 160K context.',
  },
]

// ── Derived helpers ───────────────────────────────────────────────────────────

/** All unique providers derived from the data — no hardcoding required. */
export const ALL_PROVIDERS: Provider[] = [
  ...new Set(MODEL_PRICING.map((m) => m.provider)),
]

/** All unique modalities derived from the data. */
export const ALL_MODALITIES: Modality[] = [
  ...new Set(MODEL_PRICING.map((m) => m.modality)),
] as Modality[]

export const LLM_MODELS = MODEL_PRICING.filter((m) =>
  m.modality === 'text' || m.modality === 'multimodal'
)

export interface Preset {
  id: string
  name: string
  description: string
  config: Partial<CalculatorConfig>
}

export const PRESETS: Preset[] = [
  {
    id: 'whatsapp-bot',
    name: 'WhatsApp Bot',
    description: 'Simple chatbot with short exchanges over WhatsApp',
    config: {
      taskType: 'chatbot',
      aiComponents: ['llm'],
      modelId: 'gpt-4o-mini',
      systemPromptTokens: 200,
      userMessageTokens: 80,
      assistantResponseTokens: 150,
      historyTurns: 3,
    },
  },
  {
    id: 'voice-agent',
    name: 'AI Voice Agent',
    description: 'Full voice call with STT, LLM reasoning, and TTS',
    config: {
      taskType: 'voice-call',
      aiComponents: ['llm', 'stt', 'tts'],
      modelId: 'gpt-4o',
      systemPromptTokens: 500,
      userMessageTokens: 200,
      assistantResponseTokens: 300,
      audioMinutesPerConversation: 3,
      historyTurns: 5,
    },
  },
  {
    id: 'crm-automation',
    name: 'CRM Automation',
    description: 'Structured data extraction and CRM field population',
    config: {
      taskType: 'crm',
      aiComponents: ['llm'],
      modelId: 'claude-3-5-haiku',
      systemPromptTokens: 800,
      userMessageTokens: 400,
      assistantResponseTokens: 200,
      historyTurns: 1,
    },
  },
  {
    id: 'reasoning-agent',
    name: 'Reasoning Agent',
    description: 'Deep reasoning with extended thinking and tool use',
    config: {
      taskType: 'custom',
      aiComponents: ['llm'],
      modelId: 'o3',
      systemPromptTokens: 1000,
      userMessageTokens: 500,
      assistantResponseTokens: 2000,
      reasoningMultiplier: 3,
      historyTurns: 2,
    },
  },
  {
    id: 'image-batch',
    name: 'Image Generation',
    description: 'Batch image generation with DALL-E 3',
    config: {
      taskType: 'image-generation',
      aiComponents: [],
      imageModelId: 'dall-e-3',
      imagesPerConversation: 4,
    },
  },
]
